apiVersion: v2
kubeVersion: ">= 1.24.0"
type: application
name: talos-cloud-controller-manager
description: Talos Cloud Controller Manager Helm Chart
home: https://github.com/siderolabs/talos-cloud-controller-manager
sources:
  - https://github.com/siderolabs/talos-cloud-controller-manager
keywords:
  - ccm
maintainers:
  - name: sergelogvinov
    url: https://github.com/sergelogvinov

version: 0.2.0
appVersion: "1.4.0"
